<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0-windows</TargetFramework>
        <LangVersion>preview</LangVersion>
        <PlatformTarget>x64</PlatformTarget>
        <RootNamespace>OtterGuiInternal</RootNamespace>
        <AssemblyName>OtterGuiInternal</AssemblyName>
        <FileVersion>1.0.0.0</FileVersion>
        <AssemblyVersion>1.0.0.0</AssemblyVersion>
        <Product>OtterGui</Product>
        <Copyright>Copyright © 2025</Copyright>
        <OutputType>Library</OutputType>
        <WarningLevel>4</WarningLevel>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Nullable>enable</Nullable>
        <OutputPath>bin\$(Configuration)\</OutputPath>
        <MSBuildWarningsAsMessages>$(MSBuildWarningsAsMessages);MSB3277</MSBuildWarningsAsMessages>
        <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <EnableWindowsTargeting>true</EnableWindowsTargeting>
    </PropertyGroup>

    <PropertyGroup>
        <DalamudLibPath>$(MSBuildThisFileDirectory)..\..\..\..\TC_ok\_dalamud_api13\</DalamudLibPath>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="Dalamud">
            <HintPath>$(DalamudLibPath)Dalamud.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Dalamud.Bindings.ImGui">
            <HintPath>$(DalamudLibPath)Dalamud.Bindings.ImGui.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Dalamud.Bindings.ImPlot">
            <HintPath>$(DalamudLibPath)Dalamud.Bindings.ImPlot.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="ImGuiScene">
            <HintPath>$(DalamudLibPath)ImGuiScene.dll</HintPath>
            <Private>False</Private>
        </Reference>
    </ItemGroup>
</Project>
