<Project Sdk="Microsoft.NET.Sdk">
    <!-- Project settings -->
    <PropertyGroup>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Platforms>x64</Platforms>
        <LangVersion>preview</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <PropertyGroup>
        <DalamudLibPath>$(MSBuildThisFileDirectory)..\..\..\TC_ok\_dalamud_api13\</DalamudLibPath>
    </PropertyGroup>

    <!-- Assets -->
    <ItemGroup>
        <Content Include="Assets\**\*.png" CopyToOutputDirectory="Always"/>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="Dalamud">
            <HintPath>$(DalamudLibPath)Dalamud.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="FFXIVClientStructs">
            <HintPath>$(DalamudLibPath)FFXIVClientStructs.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Lumina">
            <HintPath>$(DalamudLibPath)Lumina.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="Lumina.Excel">
            <HintPath>$(DalamudLibPath)Lumina.Excel.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="InteropGenerator.Runtime">
            <HintPath>$(DalamudLibPath)InteropGenerator.Runtime.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>
</Project>
